export const courseGroups = [
  {
    age: "AGES 7–9",
    courses: [
      {
        slug: "creative-coding",
        category: "CODING",
        title: "Creative Coding",
        description: "Learn the basics of coding through fun projects, games, and interactive activities.",
        image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&w=900&q=80",
        duration: "8 weeks",
        schedule: "Saturdays, 10:00 AM – 11:30 AM",
        tutor: "Evora Learning Team",
        topics: ["Coding Basics", "Creative Projects", "Problem Solving"],
      },
      {
        slug: "digital-creativity",
        category: "DESIGN",
        title: "Digital Creativity",
        description: "Turn ideas into colourful digital designs while discovering the world of creative technology.",
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=900&q=80",
        duration: "8 weeks",
        schedule: "Saturdays, 12:00 PM – 1:30 PM",
        tutor: "Evora Learning Team",
        topics: ["Digital Drawing", "Colour & Design", "Creative Projects", "Visual Storytelling"],
      },
      {
        slug: "tech-explorers",
        category: "TECH",
        title: "Tech Explorers",
        description: "Discover how technology works through exciting challenges, experiments, and hands-on projects.",
        image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=900&q=80",
        duration: "8 weeks",
        schedule: "Sundays, 10:00 AM – 11:30 AM",
        tutor: "Evora Learning Team",
        topics: ["Computer Basics", "How Technology Works", "Fun Tech Experiments", "Problem Solving"],
      },
    ],
  },
  {
    age: "AGES 10–12",
    courses: [
      {
        slug: "web-development",
        category: "DEVELOPMENT",
        title: "Web Development",
        description: "Build your first websites and learn how HTML, CSS, and JavaScript bring ideas to life.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80",
        duration: "10 weeks",
        schedule: "Saturdays, 10:00 AM – 11:30 AM",
        tutor: "Evora Learning Team",
        topics: ["HTML Basics", "CSS Styling", "JavaScript Fundamentals", "Building Mini Websites"],
      },
      {
        slug: "graphic-design",
        category: "CREATIVE",
        title: "Graphic Design",
        description: "Learn the principles of design and create posters, graphics, and digital experiences.",
        image: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80",
        duration: "8 weeks",
        schedule: "Saturdays, 12:00 PM – 1:30 PM",
        tutor: "Evora Learning Team",
        topics: ["Design Principles", "Colour & Typography", "Poster Design", "Creative Digital Projects"],
      },
      {
        slug: "robotics-and-innovation",
        category: "ROBOTICS",
        title: "Robotics & Innovation",
        description: "Explore robotics, problem-solving, and the exciting process of building technology.",
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80",
        duration: "10 weeks",
        schedule: "Sundays, 12:00 PM – 1:30 PM",
        tutor: "Evora Learning Team",
        topics: ["Robotics Basics", "Sensors & Components", "Building Simple Robots", "Innovation & Problem Solving"],
      },
    ],
  },
  {
    age: "AGES 13–16",
    courses: [
      {
        slug: "advanced-web-development",
        category: "DEVELOPMENT",
        title: "Advanced Web Development",
        description: "Move beyond the basics and build responsive websites with modern development tools.",
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=900&q=80",
        duration: "12 weeks",
        schedule: "Saturdays, 10:00 AM – 12:00 PM",
        tutor: "Evora Learning Team",
        topics: ["Responsive Web Design", "JavaScript Development", "React Fundamentals", "Building Real Projects"],
      },
      {
        slug: "ai-and-automation",
        category: "AI",
        title: "AI & Automation",
        description: "Understand how AI works and learn how modern AI tools can solve real-world problems.",
        image: "https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=900&q=80",
        duration: "10 weeks",
        schedule: "Sundays, 10:00 AM – 12:00 PM",
        tutor: "Evora Learning Team",
        topics: ["Introduction to AI", "AI Tools & Applications", "Automation Basics", "Real-World AI Projects"],
      },
      {
        slug: "ui-ux-design",
        category: "DESIGN",
        title: "UI/UX Design",
        description: "Learn how to design digital products that look great and are easy for people to use.",
        image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=900&q=80",
        duration: "8 weeks",
        schedule: "Sundays, 12:00 PM – 2:00 PM",
        tutor: "Evora Learning Team",
        topics: ["Design Principles", "User Interface Design", "Wireframing & Prototyping", "User Experience"],
      },
    ],
  },
];

export const courses = courseGroups.flatMap((group) => group.courses);
